services:
  backend:
    build:
      context: ./emavra-backend
      dockerfile: Dockerfile
    container_name: emavra-backend-dev
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./emavra-backend:/var/www
      - backend_storage:/var/www/storage
      - backend_cache:/var/www/bootstrap/cache
      - backend_vendor:/var/www/vendor
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=192.168.104.201
      - DB_PORT=5432
      - DB_DATABASE=emavraforestaldb_dev
      - DB_USERNAME=emavraforestal_user
      - DB_PASSWORD=emavraforestal_pass
      - APP_NAME=EmavraLocal
      - APP_ENV=development
      - APP_DEBUG=true
      - APP_URL=http://emavraforestalapidev.cochabamba.bo:8002
      - APP_KEY=base64:efdnbli2ujgcV4JEgrdhFo3eP1nUpBhGrzy7CCj3MfA=
      - FRONTEND_URL=http://emavraforestaldev.cochabamba.bo:8001
      - SANCTUM_STATEFUL_DOMAINS=emavraforestaldev.cochabamba.bo:8001
      - SESSION_DOMAIN=.cochabamba.bo
      - FILESYSTEM_DISK=public
    networks:
      - emavra_network

  nginx:
    image: nginx:alpine
    container_name: emavra-nginx-dev
    restart: unless-stopped
    ports:
      - "8002:80"
    volumes:
      - ./emavra-backend:/var/www
      - ./emavra-backend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - backend_storage:/var/www/storage
    depends_on:
      - backend
    networks:
      - emavra_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://emavraforestalapidev.cochabamba.bo:8002/api
        - REACT_APP_STORAGE_URL=http://emavraforestalapidev.cochabamba.bo:8002/storage
        - REACT_APP_MAPBOX_TOKEN=pk.eyJ1IjoiYWxlc3NpcyIsImEiOiJjbGcxbHBtbHQwdDU5M2RubDFodjY3a2x0In0.NXe43GdM4PJBj7ow0Dnkpw
    container_name: emavra-frontend-dev
    restart: unless-stopped
    ports:
      - "8001:80"
    depends_on:
      - nginx
    networks:
      - emavra_network

networks:
  emavra_network:
    driver: bridge

volumes:
  backend_storage:
    driver: local
  backend_cache:
    driver: local
  backend_vendor:
    driver: local